name: Cell Deploy

on: push

jobs:
  cell-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: npm run lint --if-present
      - run: npm test
      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        env: ${{ secrets }}
        working-directory: examples/backend-app
        run: npx cell deploy -m prod
      - if: ${{ github.ref == 'refs/heads/pre' }}
        env: ${{ secrets }}
        working-directory: examples/backend-app
        run: npx cell deploy -m pre
      - if: ${{ github.ref != 'refs/heads/master' && github.ref == 'refs/heads/main' && github.ref != 'refs/heads/pre' }}
        env: ${{ secrets }}
        working-directory: examples/backend-app
        run: npx cell deploy -m test
